### ISSUE TITLE
无法理解，那么多人对此孜孜不倦！

### ISSUE THREAD

**Issue by jingjingxyk** [justjavac/openai-proxy#1]
首先承认：技术确实很先进

我就问一个问题： 它怎么落地，谁买单？市场在哪里

我们有足够大的市场，为啥也不来国内注册一家公司进行运营。

更要命的是： 我们的头部技术人员还热衷主动送语料，供其训练，使其逐步升级进化，然后技术更先进，最后卖给谁？谁买单。

**Comment by justjavac** [comment]
首先先进的技术我们当然需要使用，这确实代表了当前 AI 领域最先进的生产力。

现在已经有很多落地的产品了

**Comment by LIUPING789** [comment]
工作上已经离不开了！

**Comment by teobler** [comment]
噗，现在的人一来就想赚钱是吗，我二次包装自己用行不行，我开源方便大家行不行

**Comment by jingjingxyk** [comment]
举个例子： 波士顿动力，波士顿动力被转手很多次。

原因是为啥？
> 1.  难道是它的技术不先进？
> 1.  难道科技不领先？ 

当然不是，技术很先进，全球领先

终极原因： 没有市场为其买单。 资本长久看不到回报，资本就会转手，进而放弃

纳闷： 为啥不来国内注册一家公司进行运营？ （技术换市场，双赢。目前看来博弈很激烈呀）

**Comment by jingjingxyk** [comment]
话说，都是GPT 套壳 吗？

**Comment by liruifengv** [comment]
yyds

**Comment by ABUGADAY** [comment]
你说电力该卖给谁？他并不需要考虑 你只要想在新时代生活 工作 生产 就离不开它

**Comment by jingjingxyk** [comment]
套壳不是长久之计，一旦 技术禁运    。。。 。。。

**Comment by jingjingxyk** [comment]
技术禁运 、脱钩  背景下  。换皮可不好存活
