### ISSUE TITLE
Cloudflare无法自定义域名，不知道是否哪里操作出错

### ISSUE THREAD

**Issue by Ssiswent** [justjavac/openai-proxy#14]
报错如图：
![image](https://user-images.githubusercontent.com/37449310/230781115-ae21f616-e639-4b7a-958c-7f1a66e7a234.png)

看起来以正常添加DNS配置
![image](https://user-images.githubusercontent.com/37449310/230781298-f41ecc45-d263-4b18-a54f-b4157e1c0dca.png)

**Comment by justjavac** [comment]
现在可以了吗，应该是改完之后等一会

**Comment by Ssiswent** [comment]
好像还是不行，有没有可能是Cloudflare在DNS添加记录时，把内容末尾的 `.` 去掉了原因。。
![image](https://user-images.githubusercontent.com/37449310/230807551-4bcb5882-5163-4b58-9c26-c16599d66090.png)
要求我添加的是这个 `xxxb737._acme.deno.dev.`
但是我添加进去之后是 `xxxb737._acme.deno.dev`

**Comment by justjavac** [comment]
结尾的点号表示“完全限定域名”。

ChatGPT 的回答：

> 在DNS中，CNAME记录用于将一个域名解析为另一个域名。例如，有一个域名“example.com”，我们可以设置一个CNAME记录将其解析为“www.example.com”。这意味着，当用户在浏览器中输入“example.com”，DNS服务器会返回“www.example.com”的IP地址。
> 
> 当在DNS记录中使用CNAME时，结尾的点号（“.”）是很重要的。它表示该记录是一个完全限定域名（FQDN），而不是相对域名。例如，假设我们有一个CNAME记录将“sub.example.com”解析为“www.example.com”。
> 
> 如果我们在记录中不使用结尾的点号： 
> sub.example.com CNAME www.example.com
> 这意味着“www.example.com”是相对于“sub.example.com”的域名，因此在解析过程中会附加“sub.example.com”中的转发区域名称（FQDN），最终将解析为“www.example.com.sub.example.com”，显然不是我们想要的结果。
> 
> 但如果我们在记录中使用结尾的点号： 
> sub.example.com. CNAME www.example.com.
> 这意味着“www.example.com”是一个完全限定的域名，不需要添加任何转发区域名称，因此可以正确地解析为“www.example.com”。

**Comment by Ssiswent** [comment]
> 结尾的点号表示“完全限定域名”。
> 
> ChatGPT 的回答：
> 
> > 在DNS中，CNAME记录用于将一个域名解析为另一个域名。例如，有一个域名“example.com”，我们可以设置一个CNAME记录将其解析为“www.example.com”。这意味着，当用户在浏览器中输入“example.com”，DNS服务器会返回“www.example.com”的IP地址。
> > 当在DNS记录中使用CNAME时，结尾的点号（“.”）是很重要的。它表示该记录是一个完全限定域名（FQDN），而不是相对域名。例如，假设我们有一个CNAME记录将“sub.example.com”解析为“www.example.com”。
> > 如果我们在记录中不使用结尾的点号：
> > sub.example.com CNAME [www.example.com](http://www.example.com)
> > 这意味着“www.example.com”是相对于“sub.example.com”的域名，因此在解析过程中会附加“sub.example.com”中的转发区域名称（FQDN），最终将解析为“www.example.com.sub.example.com”，显然不是我们想要的结果。
> > 但如果我们在记录中使用结尾的点号：
> > sub.example.com. CNAME [www.example.com](http://www.example.com).
> > 这意味着“www.example.com”是一个完全限定的域名，不需要添加任何转发区域名称，因此可以正确地解析为“www.example.com”。

原来如此，感谢~不过我暂时还没找到什么办法让Cloudflare不把末尾的 `.` 给我省略了。。
