### ISSUE TITLE
10多年前和大佬请教过问题（php的ci框架qq群），关注下。

### ISSUE THREAD

**Issue by olive1** [justjavac/openai-proxy#30]

**Comment by justjavac** [comment]
我已经不用 QQ 很多年了

**Comment by olive1** [comment]
谢谢大佬回复！我这10年一直做php，现在过了35岁，突然下岗了。也不知道做什么好。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月26日(周一) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [justjavac/openai-proxy] 10多年前和大佬请教过问题（php的ci框架qq群），关注下。 (Issue #30)




 
我已经不用 QQ 很多年了

**Comment by justjavac** [comment]
现在PHP是不是都转 go 了啊。微信聊吧，我ID： `justjavac`
