### ISSUE TITLE
The agent seems to be down?

### ISSUE THREAD

**Issue by threeColorFr** [justjavac/openai-proxy#36]
we set the own proxy 'xxxx.deno.dev/v1', it seem does not  work out from today. Can you help me. Thanks!

**Comment by justjavac** [comment]
fixed

![](https://private-user-images.githubusercontent.com/359395/295434441-28390971-03de-4189-9810-f13f47b25188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTc0MjUsIm5iZiI6MTcwNDg1NzEyNSwicGF0aCI6Ii8zNTkzOTUvMjk1NDM0NDQxLTI4MzkwOTcxLTAzZGUtNDE4OS05ODEwLWYxM2Y0N2IyNTE4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwMzI1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTIwYmU5Y2M2MzM5MGRkNDg1ZGMwNDI5OTVkYWViN2QyMDEzOTI4ZGMzZDk1YWNkN2RkMmUyZmI2ZTYyMWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lF2yNBN1oYRWynBBQyrzVeN9oznFL1IE0Efgwvc-z14)
