### ISSUE TITLE
好人一生平安，不过这么做你的服务器流量高了也会有性能问题吧

### ISSUE THREAD

**Issue by coderzzp** [justjavac/openai-proxy#4]

**Comment by justjavac** [comment]
用的是 Deno Deploy 的服务器。也可以自己部署

**Comment by lpflhh** [comment]
大神能分享一下搭建过程吗？@justjavac

**Comment by justjavac** [comment]
@lpflhh 添加到 readme 里面了

**Comment by zhanghaok** [comment]
> @lpflhh 添加到 readme 里面了

没看懂怎么搭建呜呜呜

**Comment by justjavac** [comment]
@zhanghaok 用 GitHub 账号登录 deno deploy，然后点下面的链接就可以一键搭建了
