### ISSUE TITLE
您刚弄的xxx.deno.dev我又试了一下可以了，但以前自己部署的不行。

### ISSUE THREAD

**Issue by threeColorFr** [justjavac/openai-proxy#40]
![image](https://github.com/justjavac/openai-proxy/assets/91378529/89fe308b-32e2-4e73-be94-9e2692643e9e)
您弄的这个地址我试了可以，自己以前部署的地址试了还是502，这是什么原因呢

**Comment by justjavac** [comment]
代码我更新了 https://github.com/justjavac/openai-proxy/blob/main/deno.ts

**Comment by threeColorFr** [comment]
感谢！！！

**Comment by threeColorFr** [comment]
-
