### ISSUE TITLE
使用代理地址后，返回ECONNRESET...

### ISSUE THREAD

**Issue by snwyz** [justjavac/openai-proxy#6]
如题
使用非deno代理代码连接没问题。
再使用deno部署的地址后就返回，
"request to https://closeai.deno.dev/v1/chat/completions failed, reason: read ECONNRESET"。
不知道是什么网络问题。。

**Comment by justjavac** [comment]
有可能是 dns 污染的问题。我刚试了一下，没有问题

**Comment by jessie975** [comment]
the same.
